"""add auth tokens and email verification

Revision ID: 9a8585222580
Revises: 47311753a164
Create Date: 2026-09-19 14:47:10.587949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8585222580'
down_revision: Union[str, Sequence[str], None] = '47311753a164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # NOT NULL needs a value for rows that already exist, so the column is
        # created with a server default that is dropped again below.
        batch_op.add_column(
            sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false())
        )
    # Accounts created before email verification existed are treated as verified
    # rather than being asked to confirm an address they already registered with.
    # Expressed through SQLAlchemy so the literal is correct for the dialect
    # (`= 1` is invalid for a boolean column on PostgreSQL).
    users = sa.table("users", sa.column("email_verified", sa.Boolean()))
    op.execute(users.update().values(email_verified=True))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('auth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_tokens_purpose'))

    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
